window.__INGEST_SERIES1 = {
  "issues": [
    {
      "slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1932",
      "volume": "I",
      "number": "1",
      "title": "Anuarul Arhivei de Folklor I",
      "source_pdf_name": "BCUCLUJ_FP_490809_1932_001.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1932_001.pdf",
      "article_count": 10
    },
    {
      "slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1933",
      "volume": "II",
      "number": "2",
      "title": "Anuarul Arhivei de Folklor II",
      "source_pdf_name": "BCUCLUJ_FP_490809_1933_002.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1933_002.pdf",
      "article_count": 10
    },
    {
      "slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1935",
      "volume": "III",
      "number": "3",
      "title": "Anuarul Arhivei de Folklor III",
      "source_pdf_name": "BCUCLUJ_FP_490809_1935_003.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1935_003.pdf",
      "article_count": 9
    },
    {
      "slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1937",
      "volume": "IV",
      "number": "4",
      "title": "Anuarul Arhivei de Folklor IV",
      "source_pdf_name": "BCUCLUJ_FP_490809_1937_004.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1937_004.pdf",
      "article_count": 8
    },
    {
      "slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1939",
      "volume": "V",
      "number": "5",
      "title": "Anuarul Arhivei de Folklor V",
      "source_pdf_name": "BCUCLUJ_FP_490809_1939_005.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1939_005.pdf",
      "article_count": 8
    },
    {
      "slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1942",
      "volume": "VI",
      "number": "6",
      "title": "Anuarul Arhivei de Folklor VI",
      "source_pdf_name": "BCUCLUJ_FP_490809_1942_006.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1942_006.pdf",
      "article_count": 11
    },
    {
      "slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "series_label": "Seria I (1932-1945)",
      "year": "1945",
      "volume": "VII",
      "number": "7",
      "title": "Anuarul Arhivei de Folklor VII",
      "source_pdf_name": "BCUCLUJ_FP_490809_1945_007.pdf",
      "issue_pdf_path": "ingest/series1/BCUCLUJ_FP_490809_1945_007.pdf",
      "article_count": 10
    }
  ],
  "articles": [
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 1,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Academia Română și folklorul",
      "pages_start": 2,
      "pages_end": 9,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/001-academia-romana-si-folklorul.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 2,
      "section": "",
      "author": "Artur Gorovei",
      "title": "„Șezătoarea\". Povestea vieții unei reviste de folklor",
      "pages_start": 10,
      "pages_end": 41,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/002-sezatoarea-povestea-vietii-unei-reviste-de-folklor.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 3,
      "section": "",
      "author": "V. Bogrea",
      "title": "Musca Columbacă în tradiția noastră populară și istorică (Cu o paralelă romanică)",
      "pages_start": 42,
      "pages_end": 47,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/003-musca-columbaca-in-traditia-noastra-populara-si-istorica-cu-o-paralela-romanica.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 4,
      "section": "",
      "author": "V. Bogrea",
      "title": "Trei probleme folklorice și aspectul lor românesc",
      "pages_start": 48,
      "pages_end": 53,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/004-trei-probleme-folklorice-si-aspectul-lor-romanesc.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 5,
      "section": "",
      "author": "Petru Caraman",
      "title": "Contribuție la cronologizarea și geneza baladei populare la Români. Partea I: Cronologizarea",
      "pages_start": 54,
      "pages_end": 107,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/005-contributie-la-cronologizarea-si-geneza-baladei-populare-la-romani-partea-i-cron.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 6,
      "section": "",
      "author": "Șt. Pașca",
      "title": "Nume de botez în Țara Oltului. Obiceiuri și tradiții",
      "pages_start": 108,
      "pages_end": 117,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/006-nume-de-botez-in-tara-oltului-obiceiuri-si-traditii.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 7,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Cercetări folklorice în Țara Oașului",
      "pages_start": 118,
      "pages_end": 241,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/007-cercetari-folklorice-in-tara-oasului.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 8,
      "section": "",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anul 1930",
      "pages_start": 242,
      "pages_end": 251,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/008-bibliografia-folklorului-romanesc-pe-anul-1930.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 9,
      "section": "",
      "author": "",
      "title": "Raport anual",
      "pages_start": 252,
      "pages_end": 253,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/009-raport-anual.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1932-vol-i",
      "series": "seria-1",
      "year": "1932",
      "volume": "I",
      "toc_index": 10,
      "section": "",
      "author": "",
      "title": "Résumé des articles et table des planches",
      "pages_start": 254,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1932-vol-i/articles/010-resume-des-articles-et-table-des-planches.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 1,
      "section": "",
      "author": "N. Drăganu",
      "title": "Cuvinte și obiceiuri",
      "pages_start": 2,
      "pages_end": 21,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/001-cuvinte-si-obiceiuri.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 2,
      "section": "",
      "author": "Petru Caraman",
      "title": "Contribuție la cronologizarea și geneza baladei populare la Români. Partea II. Geneza",
      "pages_start": 22,
      "pages_end": 89,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/002-contributie-la-cronologizarea-si-geneza-baladei-populare-la-romani-partea-ii-gen.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 3,
      "section": "",
      "author": "P. V. Ștefănucă",
      "title": "Folklor din județul Lăpușna",
      "pages_start": 90,
      "pages_end": 181,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/003-folklor-din-judetul-lapusna.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 4,
      "section": "",
      "author": "Ion Breazu",
      "title": "Jules Michelet și folklorul românesc",
      "pages_start": 182,
      "pages_end": 195,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/004-jules-michelet-si-folklorul-romanesc.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 5,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Variantele românești ale snoavei despre femeia necredincioasă",
      "pages_start": 196,
      "pages_end": 217,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/005-variantele-romanesti-ale-snoavei-despre-femeia-necredincioasa.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 6,
      "section": "",
      "author": "G. Bogdan-Duică",
      "title": "Încă un folklorist saxo-român",
      "pages_start": 218,
      "pages_end": 221,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/006-inca-un-folklorist-saxo-roman.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 7,
      "section": "",
      "author": "",
      "title": "Bibliografia lucrărilor de cuprins folkloric și etnografic publicate de Academia Română (1867—1930)",
      "pages_start": 222,
      "pages_end": 229,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/007-bibliografia-lucrarilor-de-cuprins-folkloric-si-etnografic-publicate-de-academia.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 8,
      "section": "",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anii 1931—1932",
      "pages_start": 230,
      "pages_end": 247,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/008-bibliografia-folklorului-romanesc-pe-anii-19311932.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 9,
      "section": "",
      "author": "",
      "title": "Raport anual (1932)",
      "pages_start": 248,
      "pages_end": 249,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/009-raport-anual-1932.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1933-vol-ii",
      "series": "seria-1",
      "year": "1933",
      "volume": "II",
      "toc_index": 10,
      "section": "",
      "author": "",
      "title": "Résumé des articles",
      "pages_start": 250,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1933-vol-ii/articles/010-resume-des-articles.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 1,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Ion Bianu și folklorul nostru",
      "pages_start": 2,
      "pages_end": 7,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/001-ion-bianu-si-folklorul-nostru.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 2,
      "section": "",
      "author": "Ion Diaconu",
      "title": "Psihologie și creație populară",
      "pages_start": 8,
      "pages_end": 25,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/002-psihologie-si-creatie-populara.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 3,
      "section": "",
      "author": "Emil Petrovici",
      "title": "Folklor din Valea Almăjului",
      "pages_start": 26,
      "pages_end": 159,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/003-folklor-din-valea-almajului.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 4,
      "section": "",
      "author": "Valeriu L. Bologa",
      "title": "Raportul din 1756 al unui chirurg german despre credințele Românilor asupra moroilor",
      "pages_start": 160,
      "pages_end": 169,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/004-raportul-din-1756-al-unui-chirurg-german-despre-credintele-romanilor-asupra-moro.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 5,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Alte variante românești ale snoavei despre femeia necredincioasă",
      "pages_start": 170,
      "pages_end": 177,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/005-alte-variante-romanesti-ale-snoavei-despre-femeia-necredincioasa.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 6,
      "section": "",
      "author": "P. V. Ștefănucă",
      "title": "Contribuție la bibliografia studiilor și culegerilor de folklor privitoare la Românii din Basarabia și popoarele conlocuitoare — publicate în periodicele rusești",
      "pages_start": 178,
      "pages_end": 189,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/006-contributie-la-bibliografia-studiilor-si-culegerilor-de-folklor-privitoare-la-ro.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 7,
      "section": "",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anii 1933—34",
      "pages_start": 190,
      "pages_end": 211,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/007-bibliografia-folklorului-romanesc-pe-anii-193334.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 8,
      "section": "",
      "author": "",
      "title": "Raport anual (1933—34)",
      "pages_start": 212,
      "pages_end": 213,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/008-raport-anual-193334.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1935-vol-iii",
      "series": "seria-1",
      "year": "1935",
      "volume": "III",
      "toc_index": 9,
      "section": "",
      "author": "",
      "title": "Résumé des articles",
      "pages_start": 214,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1935-vol-iii/articles/009-resume-des-articles.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 1,
      "section": "",
      "author": "Silviu Dragomir",
      "title": "Scriitorii raguzani și refrenul colindelor noastre",
      "pages_start": 6,
      "pages_end": 13,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/001-scriitorii-raguzani-si-refrenul-colindelor-noastre.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 2,
      "section": "",
      "author": "D. St. Petruțiu",
      "title": "«Mironosițele». O dramă religioasă din ținutul Săliștei",
      "pages_start": 14,
      "pages_end": 31,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/002-mironositele-o-drama-religioasa-din-tinutul-salistei.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 3,
      "section": "",
      "author": "P. V. Ștefănucă",
      "title": "Cercetări folklorice în Valea Nistrului-de-Jos",
      "pages_start": 32,
      "pages_end": 229,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/003-cercetari-folklorice-in-valea-nistrului-de-jos.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 4,
      "section": "",
      "author": "Tiberiu Morariu",
      "title": "Contribuțiuni la aprinderea «focului viu» în Ardeal, Maramureș și Bucovina",
      "pages_start": 230,
      "pages_end": 237,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/004-contributiuni-la-aprinderea-focului-viu-in-ardeal-maramures-si-bucovina.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 5,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Materiale pentru cunoașterea răspândirii «focului viu» la Români",
      "pages_start": 238,
      "pages_end": 243,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/005-materiale-pentru-cunoasterea-raspandirii-focului-viu-la-romani.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 6,
      "section": "",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anul 1935",
      "pages_start": 244,
      "pages_end": 263,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/006-bibliografia-folklorului-romanesc-pe-anul-1935.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 7,
      "section": "",
      "author": "",
      "title": "Raport anual (1935—36)",
      "pages_start": 264,
      "pages_end": 265,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/007-raport-anual-193536.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1937-vol-iv",
      "series": "seria-1",
      "year": "1937",
      "volume": "IV",
      "toc_index": 8,
      "section": "",
      "author": "",
      "title": "Résumé des articles",
      "pages_start": 266,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1937-vol-iv/articles/008-resume-des-articles.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 1,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Ovid Densusianu folklorist",
      "pages_start": 2,
      "pages_end": 7,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/001-ovid-densusianu-folklorist.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 2,
      "section": "",
      "author": "N. P. Smochină",
      "title": "Din literatura populară a Românilor de peste Nistru",
      "pages_start": 8,
      "pages_end": 57,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/002-din-literatura-populara-a-romanilor-de-peste-nistru.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 3,
      "section": "",
      "author": "Traian German",
      "title": "Tovărășiile de Crăciun ale feciorilor români din Ardeal",
      "pages_start": 58,
      "pages_end": 79,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/003-tovarasiile-de-craciun-ale-feciorilor-romani-din-ardeal.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 4,
      "section": "",
      "author": "Ion Breazu",
      "title": "Versuri populare în manuscrise ardelene vechi",
      "pages_start": 80,
      "pages_end": 111,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/004-versuri-populare-in-manuscrise-ardelene-vechi.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 5,
      "section": "",
      "author": "Emil Petrovici",
      "title": "Folklor dela Moții din Scărișoara",
      "pages_start": 112,
      "pages_end": 177,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/005-folklor-dela-motii-din-scarisoara.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 6,
      "section": "",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anii 1936—1937",
      "pages_start": 178,
      "pages_end": 213,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/006-bibliografia-folklorului-romanesc-pe-anii-19361937.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 7,
      "section": "",
      "author": "",
      "title": "Raport anual (1937-38)",
      "pages_start": 214,
      "pages_end": 215,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/007-raport-anual-1937-38.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1939-vol-v",
      "series": "seria-1",
      "year": "1939",
      "volume": "V",
      "toc_index": 8,
      "section": "",
      "author": "",
      "title": "Résumé des articles",
      "pages_start": 216,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1939-vol-v/articles/008-resume-des-articles.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 1,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Prefață",
      "pages_start": 2,
      "pages_end": 5,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/001-prefata.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 2,
      "section": "",
      "author": "D. Prodan",
      "title": "Versuri contemporane despre răscoala lui Horea",
      "pages_start": 6,
      "pages_end": 33,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/002-versuri-contemporane-despre-rascoala-lui-horea.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 3,
      "section": "",
      "author": "Gh. Pavelescu",
      "title": "Pasărea-suflet",
      "pages_start": 34,
      "pages_end": 43,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/003-pasarea-suflet.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 4,
      "section": "",
      "author": "Emil Petrovici",
      "title": "Note de folklor dela Românii Valea Mlavei (Sârbia)",
      "pages_start": 44,
      "pages_end": 77,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/004-note-de-folklor-dela-romanii-valea-mlavei-sarbia.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 5,
      "section": "",
      "author": "P. V. Ștefănucă",
      "title": "O familie de povestitori din Iurceni (Basarabia)",
      "pages_start": 78,
      "pages_end": 101,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/005-o-familie-de-povestitori-din-iurceni-basarabia.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 6,
      "section": "",
      "author": "Ion Mărcuș",
      "title": "Preocupările folklorice ale teologilor sibieni în anii 1871—1907",
      "pages_start": 102,
      "pages_end": 123,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/006-preocuparile-folklorice-ale-teologilor-sibieni-in-anii-18711907.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 7,
      "section": "",
      "author": "Vasile Scurtu",
      "title": "Cercetări folklorice în Ugocea românească",
      "pages_start": 124,
      "pages_end": 301,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/007-cercetari-folklorice-in-ugocea-romaneasca.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 8,
      "section": "",
      "author": "Elisabeta Nanu",
      "title": "Un manuscris cu Irozi al lui Picu Pătruț",
      "pages_start": 302,
      "pages_end": 329,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/008-un-manuscris-cu-irozi-al-lui-picu-patrut.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 9,
      "section": "",
      "author": "Ion Pătruț",
      "title": "Folklor dela Românii din Sârbia",
      "pages_start": 330,
      "pages_end": 385,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/009-folklor-dela-romanii-din-sarbia.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 10,
      "section": "",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anul 1938",
      "pages_start": 386,
      "pages_end": 423,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/010-bibliografia-folklorului-romanesc-pe-anul-1938.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1942-vol-vi",
      "series": "seria-1",
      "year": "1942",
      "volume": "VI",
      "toc_index": 11,
      "section": "",
      "author": "",
      "title": "Résumé des articles",
      "pages_start": 424,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1942-vol-vi/articles/011-resume-des-articles.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 1,
      "section": "",
      "author": "Artur Gorovei",
      "title": "M. Gaster și folklorul românesc",
      "pages_start": 2,
      "pages_end": 5,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/001-m-gaster-si-folklorul-romanesc.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 2,
      "section": "",
      "author": "Ion Mușlea",
      "title": "Prefață",
      "pages_start": 6,
      "pages_end": 12,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/002-prefata.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 3,
      "section": "",
      "author": "Tatiana Gălușcă",
      "title": "„Mocanii\". Un joc dramatic al Românilor din Dobrogea",
      "pages_start": 13,
      "pages_end": 35,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/003-mocanii-un-joc-dramatic-al-romanilor-din-dobrogea.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 4,
      "section": "",
      "author": "Gh. Pavelescu",
      "title": "Cercetări folklorice în Sudul județului Bihor",
      "pages_start": 36,
      "pages_end": 123,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/004-cercetari-folklorice-in-sudul-judetului-bihor.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 5,
      "section": "ARTICOLE MĂRUNTE",
      "author": "Enea Hodoș",
      "title": "„Din activitatea mea de folklorist\"",
      "pages_start": 124,
      "pages_end": 128,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/005-din-activitatea-mea-de-folklorist.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 6,
      "section": "ARTICOLE MĂRUNTE",
      "author": "Ion Mușlea",
      "title": "Practici magice și denumirea lor în circularele episcopești și protopopești dela începutul veacului trecut",
      "pages_start": 129,
      "pages_end": 130,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/006-practici-magice-si-denumirea-lor-in-circularele-episcopesti-si-protopopesti-dela.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 7,
      "section": "ARTICOLE MĂRUNTE",
      "author": "Gh. Pavelescu",
      "title": "Despre „pasărea — suflet\"",
      "pages_start": 131,
      "pages_end": 131,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/007-despre-pasarea-suflet.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 8,
      "section": "ARTICOLE MĂRUNTE",
      "author": "Romulus Todoran",
      "title": "Poezii populare într'un manuscris ardelean din 1831",
      "pages_start": 132,
      "pages_end": 140,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/008-poezii-populare-intr-un-manuscris-ardelean-din-1831.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 9,
      "section": "ARTICOLE MĂRUNTE",
      "author": "",
      "title": "Bibliografia folklorului românesc pe anii 1939—1943",
      "pages_start": 141,
      "pages_end": 199,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/009-bibliografia-folklorului-romanesc-pe-anii-19391943.pdf"
    },
    {
      "issue_slug": "aaf-seria1-1945-vol-vii",
      "series": "seria-1",
      "year": "1945",
      "volume": "VII",
      "toc_index": 10,
      "section": "ARTICOLE MĂRUNTE",
      "author": "",
      "title": "Résumé des articles",
      "pages_start": 200,
      "pages_end": null,
      "article_pdf_path": "ingest/series1/issues/aaf-seria1-1945-vol-vii/articles/010-resume-des-articles.pdf"
    }
  ]
};
